help_plus = """
HERE IS HELP FOR BARCODES :-
✣ {AZx00} - SCAMMER.
✣ {AZx01} - SPAM ADDING MEMBER.
✣ {AZx03} - ABUSE SPAM.
✣ {AZx04} - NSFW SPAMMER.
✣ {AZx06} - IMPERSONATION.
✣ {AZx07} - MD/BTC SCAM.
✣ {AZx08} - ADDING SPAMBOTS.
✣ {AZx10} - ILLEGAL.
✣ {AZx11} - PHISHING.
✣ {AZx12} - FRAUD PROMOTION  [ANY KIND].
✣ {AZx13} - CYBER THREATENING / CYBER BULLY.
✣ {AZx14} - CHILD ABUSE.
✣ {AZx15} - BAN EVASION.
✣ {AZx16} - SPAMBOT.
✣ {AZx17} - RAID INITIALIZOR. 
✣ {AZx18} - RAID PARTICIPANT.
✣ {AZx19} - KRIMINALANT.

✣ {AZx20} - RAID/SPAM INFLAMMER.

✣ {RD-00} - RAID // SCAMMER BAN BY SCANNER BOT'S REPORTS
"""

__plugin_name__ = "Bancodes"
